### ISSUE TITLE
Broken in v15

### ISSUE THREAD

**Issue by dbalders** [4D/vc-framework-v14#5]
Hello,

Is there a way to get this to work with v15? Or is there a v15 version people are using somewhere?

Thanks,
David Balderston

**Comment by tpenner** [comment]
I use it on v15 and have no issue; what is the issue you are having?

**Comment by dbalders** [comment]
@tpenner oh really? Huh. It is just no longer writing out any new file changes. I upgraded and re-built vc_framework to v15, and then upgraded my database to v15 and now it doesn't seem like it is tracking anymore.

**Comment by tpenner** [comment]
what version of 4D (server, standalone, 32 bit, 64 bit) and what platform (mac or windows)?

**Comment by tpenner** [comment]
On Startup i am calling:

    // VC Framework
    C_LONGINT($vc_found_l)
    ARRAY TEXT($vc_components_at;0)
    COMPONENT LIST($vc_components_at)
    $vc_found_l:=Find in array($vc_components_at;"VC_Framework")
    If ($vc_found_l>0)
        EXECUTE METHOD("VC_STARTUP";*)
    End if

**Comment by tpenner** [comment]
@dbalders are you using **4D Server 64 bit on MacOS**  - I am pretty sure it needs to be recompiled for that specific case. 

See here: http://doc.4d.com/4Dv15R4/4D/15-R4/Using-4D-Server-64-bit-version-OS-X.300-2917374.en.html#2292670

> ### Compiled Code Compatibility  

> In order to support OS X 64-bit architecture, the 4D built-in compiler was modified. Consequently, only databases compiled with 4D v15 or higher (Note: the modification of the compiler has been effective since 4D v14 R3)  can run on OS X 64-bit. This means that:
* if you want to use existing 4D databases on OS X 64-bit in compiled mode, you need to recompile them with 4D v15 (or higher),
* if your databases use compiled components, you need to recompile the components with 4D v15 (or higher).

**Comment by dbalders** [comment]
@tpenner thanks! Ya i am using MacOS 64 bit. I recompiled and added your startup code (was just letting it do its thing with no added code before). Here is something weird. If I add the interpreted vc_framework to the components folder, it started working. Once i compile it (in v15), and add that to the components folder, it stops working. That doesn't seem to make sense

**Comment by dbalders** [comment]
Not that big of a deal to keep it interpreted, just weird that it wouldn't work once compiled

**Comment by tpenner** [comment]
@dbalders I just [downloaded][1] the component again and tested 4D Server 64 bit for MacOS using [15.2][2] (build 198931) with the compiled [Components][3] from this repository. I did not recompile the component. All i did was add the startup code to On Server Startup via the ["VC_Framework: Startup Install"][4] macro. For me this worked. I can provide you the sample database if you like.

[1]: https://github.com/4D/vc-framework-v14/archive/master.zip
[2]: http://download.4d.com/Products/Current/4D_v15_2/Installers/4D_v15_2_Mac.dmg
[3]: https://github.com/4D/vc-framework-v14/tree/master/Components
[4]: https://github.com/4D/vc-framework-v14#activation-at-startup

**Comment by dbalders** [comment]
Thanks @tpenner. I think I am good to go now, so no need to send the sample database. Thank you for taking the time help and provide example code for me. Really really appreciate it.
